//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenjaminShirk_Prog_POE_Part2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ST10081854DatabaseEntities : DbContext
    {
        public ST10081854DatabaseEntities()
            : base("name=ST10081854DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLEmployee> TBLEmployees { get; set; }
        public virtual DbSet<TBLFarmer> TBLFarmers { get; set; }
        public virtual DbSet<TBLLogin> TBLLogins { get; set; }
        public virtual DbSet<TBLProduct> TBLProducts { get; set; }
    }
}
