//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenjaminShirk_Prog_POE_Part2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLProduct
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string Quantity { get; set; }
        public int FarmerID { get; set; }
    
        public virtual TBLFarmer TBLFarmer { get; set; }
    }
}
